@base_url = http://localhost:5228/api

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST {{base_url}}/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Batata",
    "cpf" : "14603674996"
}

### Obtenção de todos os funcionários
GET {{base_url}}/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST {{base_url}}/folha/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 50,
    "mes" : 12,
    "ano" : 2023,
    "funcionarioId" : 6
}

### Obtenção de todas as folhas
GET {{base_url}}/folha/listar

### Obtenção de uma folha
GET {{base_url}}/folha/buscar/14603674996/12/2023